version: "3.9"
services:
  site:
    ports:
      - "3000:3000"
    build:
      context: ../../
      dockerfile: ./docker/dev/Dockerfile
    volumes:
      - ../../site/src:/root/src:ro
      - ../../site/public:/root/public:ro
