networks:
  app-network:
    name: app-network
    external: true
  tool-network:
    name: tool-network
    external: true
  mcp-network:
    name: mcp-network
    external: true

services:
  infra-cloudflared:
    container_name: infra-cloudflared
    image: cloudflare/cloudflared
    restart: unless-stopped
    env_file: ./.env
    environment:
      - TUNNEL_TOKEN=$CLOUDFLARE_TUNNEL_TOKEN
    command: tunnel --no-autoupdate run
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - app-network
      - tool-network
      - mcp-network
