version: '3.9'
services:
  nginx:
    image: nginx:1.27.1-alpine
    container_name: nginx
    ports:
      - '10000:80'
    volumes:
      - ./apps/nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
      - ./cert:/etc/nginx/cert:ro
    restart: always

  site-nathan:
    image: site-nathan
    container_name: site-nathan
    build:
      context: ./apps/site-nathan
      dockerfile: Dockerfile.dev
    ports:
      - '10100:10100'
    restart: always
    volumes:
      - ./apps/site-nathan/src:/root/src:ro
      - ./apps/site-nathan/public:/root/public:ro

  server-i18next-websocket:
    image: server-i18next-websocket
    container_name: server-i18next-websocket
    build:
      context: ./apps/server-i18next-websocket
      dockerfile: Dockerfile.dev
    ports:
      - '10200:10200'
    restart: always
    volumes:
      - ./apps/server-i18next-websocket/src:/root/src:ro
