services:
  cloudflared:
    container_name: cloudflare-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    env_file: ./.env
    environment:
      - TUNNEL_TOKEN=$CLOUDFLARE_TUNNEL_TOKEN
    command: tunnel --no-autoupdate run

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    env_file: ./.env
    environment:
      - WATCHTOWER_HTTP_API_TOKEN=$WATCHTOWER_HTTP_API_TOKEN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.docker/config.json:/config.json
    command: |-
      --schedule "0 0 9 * * *"
      --http-api-update
      --http-api-periodic-polls
      --cleanup
      --include-stopped
      --revive-stopped
      --stop-timeout 30s
      demasie-proxy
      nathan-app-habit-print
      nathan-app-referral-codes
      nathan-app-site
      nathan-edu-i18next-server

  demasie-proxy:
    container_name: demasie-proxy
    image: ghcr.io/ndemasie/demasie-proxy:latest
    ports:
      - '9000:9000' # watchtower
      - '10000:10000' # nathan-app-site
      - '10100:10100' # nathan-app-site
      - '10150:10150' # natalie-app-site
      - '10200:10200' # nathan-edu-i18next-server
      - '10300:10300' # nathan-app-habit-print
      - '10400:10400' # nathan-app-referral-codes
    restart: unless-stopped

  nathan-app-site:
    container_name: nathan-app-site
    image: ghcr.io/ndemasie/nathan-app-site:latest
    restart: unless-stopped

  nathan-edu-i18next-server:
    container_name: nathan-edu-i18next-server
    image: ghcr.io/ndemasie/nathan-edu-i18next-server:latest
    restart: unless-stopped

  nathan-app-habit-print:
    container_name: nathan-app-habit-print
    image: ghcr.io/ndemasie/nathan-app-habit-print:latest
    restart: unless-stopped

  nathan-app-referral-codes:
    container_name: nathan-app-referral-codes
    image: ghcr.io/ndemasie/nathan-app-referral-codes:latest
    restart: unless-stopped
