services:
  infra-cloudflared:
    container_name: infra-cloudflared
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    env_file: ./.env
    command:
      - tunnel
      - --no-autoupdate
      - --config
      - /etc/cloudflared/config.yml
      - run
      - --token
      - $CLOUDFLARE_TUNNEL_TOKEN
    volumes:
      - ./packages/infra-cloudflared/config.yml:/etc/cloudflared/config.yml:ro
    network_mode: host
