networks:
  network-mcp:
    name: network-mcp
    external: true

services:
  mcp-brave-search:
    container_name: mcp-brave-search
    image: mcp/brave-search
    ports:
      - '8080:8080'
    env_file: ./.env
    restart: unless-stopped
    networks:
      - network-mcp

  mcp-time:
    container_name: mcp-time
    build:
      context: ./packages/mcp-time
      dockerfile: Dockerfile.prod
    ports:
      - '8090:8000'
    networks:
      - network-mcp
