version: "3.9"
services:
  nginx:
    image: my-nginx:latest
    build:
      context: ./apps/nginx
      dockerfile: Dockerfile.prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/nathan.demasie.com/fullchain.pem:/etc/letsencrypt/live/nathan.demasie.com/fullchain.pem:ro
      - /etc/letsencrypt/live/nathan.demasie.com/privkey.pem:/etc/letsencrypt/live/nathan.demasie.com/privkey.pem:ro
    restart: always

  homepage:
    image: my-homepage:latest
    build:
      context: ./apps/homepage
      dockerfile: Dockerfile.prod
    restart: always

  server-i18next-websocket:
    image: my-server-i18next-websocket:latest
    build:
      context: ./apps/server-i18next-websocket
      dockerfile: Dockerfile.prod
    restart: always