networks:
  app-network:
    name: app-network
    external: true

services:
  app-proxy:
    container_name: app-proxy
    image: ghcr.io/ndemasie/app-proxy:latest
    ports:
      - '10100:10100' # app-site
      - '10150:10150' # natalie-app-site
      - '10200:10200' # edu-i18next-server
      - '10300:10300' # app-habit-print
      - '10400:10400' # app-refer-codes
    restart: unless-stopped
    networks:
      - app-network

  app-site:
    container_name: app-site
    image: ghcr.io/ndemasie/app-site:latest
    restart: unless-stopped
    networks:
      - app-network

  edu-i18next-server:
    container_name: edu-i18next-server
    image: ghcr.io/ndemasie/edu-i18next-server:latest
    restart: unless-stopped
    networks:
      - app-network

  app-habit-print:
    container_name: app-habit-print
    image: ghcr.io/ndemasie/app-habit-print:latest
    restart: unless-stopped
    networks:
      - app-network

  app-refer-codes:
    container_name: app-refer-codes
    image: ghcr.io/ndemasie/app-refer-codes:latest
    restart: unless-stopped
    networks:
      - app-network
