version: '3.9'
services:
  # cloudflared:
  #   image: cloudflare/cloudflared
  #   container_name: cloudflare-tunnel
  #   restart: unless-stopped
  #   command: tunnel --no-autoupdate run
  #   env_file: ./.env
  #   environment:
  #     - TUNNEL_TOKEN=$CLOUDFLARE_TUNNEL_TOKEN

  nginx:
    image: nginx:1.27.3-alpine
    container_name: nginx
    ports:
      - '80:80' # site-nathan, server-i18next-websocket
      - '443:443' # site-nathan, server-i18next-websocket
      - '10300:10300' # app-habit-print
      - '10400:10400' # app-referral-codes
    volumes:
      - ./packages/nginx/prod/conf.d:/etc/nginx/conf.d:ro
      - ./packages/nginx/prod/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

  site-nathan:
    image: site-nathan
    container_name: site-nathan
    build:
      context: ./packages/site-nathan
      dockerfile: Dockerfile.prod
    restart: unless-stopped

  server-i18next-websocket:
    image: server-i18next-websocket
    container_name: server-i18next-websocket
    build:
      context: ./packages/server-i18next-websocket
      dockerfile: Dockerfile.prod
    restart: unless-stopped

  app-habit-print:
    image: app-habit-print
    container_name: app-habit-print
    build:
      context: ./packages/app-habit-print
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    volumes:
      - ./packages/app-habit-print/src:/root/src:ro

  app-referral-codes:
    image: app-referral-codes
    container_name: app-referral-codes
    build:
      context: ./packages/app-referral-codes
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    volumes:
      - ./packages/app-referral-codes/src:/root/src:ro
