services:
  tool-proxy:
    container_name: tool-proxy
    image: ghcr.io/ndemasie/tool-proxy:latest
    ports:
      - '9000:9000' # tool-watchtower
    restart: unless-stopped

  tool-n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: tool-n8n
    restart: always
    env_file:
      - ./packages/tool-n8n/.base.env
      - ./packages/tool-n8n/.prod.env
    command: start --tunnel
    volumes:
      - ./packages/tool-n8n/.volume:/home/node/.n8n:rw

  tool-watchtower:
    container_name: tool-watchtower
    image: containrrr/watchtower
    env_file: ./.env
    environment:
      - WATCHTOWER_HTTP_API_TOKEN=$WATCHTOWER_HTTP_API_TOKEN
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.docker/config.json:/config.json
    command: |-
      --schedule "0 0 9 * * *"
      --http-api-update
      --http-api-periodic-polls
      --cleanup
      --include-stopped
      --revive-stopped
      --stop-timeout 30s
      demasie-proxy
      nathan-app-habit-print
      nathan-app-refer-codes
      nathan-app-site
      nathan-edu-i18next-server
