# networks:
#   tool-network:

services:
  # tool-traefik:
  #   container_name: tool-traefik
  #   image: traefik
  #   ports:
  #     - '80:80'
  #     - '443:443'
  #   networks:
  #     - tool-network
  #   restart: unless-stopped
  #   env_file: ./.env
  #   command:
  #     - '--api.insecure=true'
  #     - '--providers.docker=true'
  #     - '--providers.docker.exposedbydefault=false'
  #     - '--entrypoints.web.address=:80'
  #     - '--entrypoints.web.http.redirections.entryPoint.to=websecure'
  #     - '--entrypoints.web.http.redirections.entrypoint.scheme=https'
  #     - '--entrypoints.websecure.address=:443'
  #     - '--certificatesresolvers.mytlschallenge.acme.tlschallenge=true'
  #     - '--certificatesresolvers.mytlschallenge.acme.email=${SSL_EMAIL}'
  #     - '--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json'
  #   volumes:
  #     - ./.volume/tool-traefik:/letsencrypt
  #     - /var/run/docker.sock:/var/run/docker.sock:ro

  tool-n8n:
    container_name: tool-n8n
    build:
      context: ./packages/tool-n8n
      dockerfile: Dockerfile
    ports:
      - '5678:5678'
    # networks:
    #   - tool-network
    restart: unless-stopped
    env_file:
      - ./packages/tool-n8n/.base.env
      - ./packages/tool-n8n/.prod.env
    labels:
      - traefik.enable=true
      - traefik.http.routers.tool-n8n.rule=Host(`tool-n8n.${DOMAIN}`)
      - traefik.http.routers.tool-n8n.tls=true
      - traefik.http.routers.tool-n8n.entrypoints=websecure
      - traefik.http.routers.tool-n8n.tls.certresolver=mytlschallenge
      - traefik.http.routers.tool-n8n.middlewares=tool-n8n@docker
      - traefik.http.middlewares.tool-n8n.headers.SSLRedirect=true
      - traefik.http.middlewares.tool-n8n.headers.STSSeconds=315360000
      - traefik.http.middlewares.tool-n8n.headers.browserXSSFilter=true
      - traefik.http.middlewares.tool-n8n.headers.contentTypeNosniff=true
      - traefik.http.middlewares.tool-n8n.headers.forceSTSHeader=true
      - traefik.http.middlewares.tool-n8n.headers.SSLHost=${DOMAIN}
      - traefik.http.middlewares.tool-n8n.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.tool-n8n.headers.STSPreload=true
    volumes:
      - ./.volume/tool-n8n:/home/node/.n8n
      - ./.volume/local-files:/files
