version: '3.9'
services:
  nginx:
    image: demasie-nginx
    build:
      context: ./apps/nginx
      dockerfile: Dockerfile.prod
    ports:
      - '80:80'
      - '443:443'
    environment:
      - CERTBOT_EMAIL=$CERTBOT_EMAIL
    volumes:
      - nginx_secrets:/etc/letsencrypt
    restart: unless-stopped

  site-nathan:
    image: demasie-site-nathan
    build:
      context: ./apps/site-nathan
      dockerfile: Dockerfile.prod
    restart: unless-stopped

  server-i18next-websocket:
    image: demasie-server-i18next-websocket
    build:
      context: ./apps/server-i18next-websocket
      dockerfile: Dockerfile.prod
    restart: unless-stopped

volumes:
  nginx_secrets:
