version: '3.9'
services:
  nginx:
    image: nginx
    ports:
      - '10000:80'
    volumes:
      - ./apps/nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
      - ./cert:/etc/nginx/cert:ro
    restart: always

  homepage:
    build:
      context: ./apps/homepage
      dockerfile: Dockerfile.dev
    ports:
      - '10100:10100'
    restart: always
    volumes:
      - ./apps/homepage/src:/root/src:ro
      - ./apps/homepage/public:/root/public:ro

  server-i18next-websocket:
    build:
      context: ./apps/server-i18next-websocket
      dockerfile: Dockerfile.dev
    ports:
      - '10200:10200'
    restart: always
    volumes:
      - ./apps/server-i18next-websocket/src:/root/src:ro
