services:
  tool-proxy:
    container_name: tool-proxy
    build:
      context: ./packages/tool-proxy
      dockerfile: Dockerfile.prod
    ports:
      # - '9000:9000' # tool-watchtower
      - '5678:5678' # tool-n8n
    restart: unless-stopped
    volumes:
      - ./packages/tool-proxy/conf.d:/etc/nginx/conf.d:ro
      - ./packages/tool-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cert:/etc/nginx/cert:ro

  tool-n8n:
    container_name: tool-n8n
    build:
      context: ./packages/tool-n8n
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./packages/tool-n8n/.base.env
      - ./packages/tool-n8n/.prod.env
    ports:
      - '5678:5678'
    labels:
      - traefik.enable=true
      - traefik.http.routers.n8n.rule=Host(`tool-n8n.demasie.com`)
      - traefik.http.routers.n8n.tls=true
      - traefik.http.routers.n8n.entrypoints=web,websecure
      - traefik.http.routers.n8n.tls.certresolver=mytlschallenge
      - traefik.http.middlewares.n8n.headers.SSLRedirect=true
      - traefik.http.middlewares.n8n.headers.STSSeconds=315360000
      - traefik.http.middlewares.n8n.headers.browserXSSFilter=true
      - traefik.http.middlewares.n8n.headers.contentTypeNosniff=true
      - traefik.http.middlewares.n8n.headers.forceSTSHeader=true
      - traefik.http.middlewares.n8n.headers.SSLHost=demasie.com
      - traefik.http.middlewares.n8n.headers.STSIncludeSubdomains=true
      - traefik.http.middlewares.n8n.headers.STSPreload=true
      - traefik.http.routers.n8n.middlewares=n8n@docker
    volumes:
      - ./.volume/tool-n8n:/home/node/.n8n
      - ./.volume/local-files:/files
