version: '3.9'
services:
  nginx:
    image: nginx:1.27.3-alpine
    container_name: nginx
    ports:
      - '10000:80' # site-nathan
      - '10100:10100' # site-nathan
      - '10200:10200' # server-i18next-websocket
      - '10300:10300' # app-habit-print
      - '10400:10400' # app-referral-codes
    volumes:
      - ./packages/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./packages/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cert:/etc/nginx/cert:ro
    restart: always

  site-nathan:
    image: site-nathan
    container_name: site-nathan
    build:
      context: ./packages/site-nathan
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./packages/site-nathan/src:/root/src:ro
      - ./packages/site-nathan/public:/root/public:ro

  server-i18next-websocket:
    image: server-i18next-websocket
    container_name: server-i18next-websocket
    build:
      context: ./packages/server-i18next-websocket
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./packages/server-i18next-websocket/src:/root/src:ro

  app-habit-print:
    image: app-habit-print
    container_name: app-habit-print
    build:
      context: ./packages/app-habit-print
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./packages/app-habit-print/src:/root/src:ro

  app-referral-codes:
    image: app-referral-codes
    container_name: app-referral-codes
    build:
      context: ./packages/app-referral-codes
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./packages/app-referral-codes/src:/root/src:ro
      - ./packages/app-referral-codes/public:/root/public:ro
