version: "3.9"
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./apps/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/nathan.demasie.com/fullchain.pem:/etc/letsencrypt/live/nathan.demasie.com/fullchain.pem:ro
      - /etc/letsencrypt/live/nathan.demasie.com/privkey.pem:/etc/letsencrypt/live/nathan.demasie.com/privkey.pem:ro
    restart: always
    depends_on:
      - homepage
      - server-i18next-websocket

  homepage:
    image: homepage:latest
    build:
      context: ./apps/homepage
      dockerfile: Dockerfile.prod
    restart: always

  server-i18next-websocket:
    image: server-i18next-websocket:latest
    build:
      context: ./apps/server-i18next-websocket
      dockerfile: Dockerfile.prod
    restart: always