networks:
  default:
    name: tool-network

services:
  tool-proxy:
    container_name: tool-proxy
    build:
      context: ./packages/tool-proxy
      dockerfile: Dockerfile.prod
    ports:
      # - '9000:9000' # tool-watchtower
      - '5678:5678' # tool-n8n
    restart: unless-stopped
    volumes:
      - ./packages/tool-proxy/conf.d:/etc/nginx/conf.d:ro
      - ./packages/tool-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cert:/etc/nginx/cert:ro

  tool-n8n:
    container_name: tool-n8n
    build:
      context: ./packages/tool-n8n
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./packages/tool-n8n/.base.env
      - ./packages/tool-n8n/.prod.env
    command: ['start', '--tunnel']
    environment:
      - NODE_ENV=production
    volumes:
      - ./.volume/tool-n8n:/home/node/.n8n
