networks:
  app-network:

services:
  demasie-proxy:
    container_name: demasie-proxy
    image: ghcr.io/ndemasie/demasie-proxy:latest
    ports:
      - '10100:10100' # nathan-app-site
      - '10150:10150' # natalie-app-site
      - '10200:10200' # nathan-edu-i18next-server
      - '10300:10300' # nathan-app-habit-print
      - '10400:10400' # nathan-app-refer-codes
    restart: unless-stopped

  nathan-app-site:
    container_name: nathan-app-site
    image: ghcr.io/ndemasie/nathan-app-site:latest
    restart: unless-stopped

  nathan-edu-i18next-server:
    container_name: nathan-edu-i18next-server
    image: ghcr.io/ndemasie/nathan-edu-i18next-server:latest
    restart: unless-stopped

  nathan-app-habit-print:
    container_name: nathan-app-habit-print
    image: ghcr.io/ndemasie/nathan-app-habit-print:latest
    restart: unless-stopped

  nathan-app-refer-codes:
    container_name: nathan-app-refer-codes
    image: ghcr.io/ndemasie/nathan-app-refer-codes:latest
    restart: unless-stopped
