services:
  # cloudflared:
  #   container_name: cloudflare-tunnel
  #   image: cloudflare/cloudflared
  #   restart: unless-stopped
  #   command: tunnel --no-autoupdate run
  #   env_file: ./.env
  #   environment:
  #     - TUNNEL_TOKEN=$CLOUDFLARE_TUNNEL_TOKEN

  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME/.docker/config.json:/config.json
    command: |-
      --interval 30
      nginx
      site-nathan
      server-i18next-websocket
      app-habit-print
      app-referral-codes

  nginx:
    container_name: nginx
    image: ghcr.io/ndemasie/nginx-demasie:latest
    ports:
      - '10000:80' # site-nathan
      - '10100:10100' # site-nathan
      - '10200:10200' # server-i18next-websocket
      - '10300:10300' # app-habit-print
      - '10400:10400' # app-referral-codes
    restart: unless-stopped

  site-nathan:
    container_name: site-nathan
    image: ghcr.io/ndemasie/site-nathan:latest
    restart: unless-stopped

  server-i18next-websocket:
    container_name: server-i18next-websocket
    image: ghcr.io/ndemasie/server-i18next-websocket:latest
    restart: unless-stopped

  app-habit-print:
    container_name: app-habit-print
    image: ghcr.io/ndemasie/app-habit-print:latest
    restart: unless-stopped

  app-referral-codes:
    container_name: app-referral-codes
    image: ghcr.io/ndemasie/app-referral-codes:latest
    restart: unless-stopped
