services:
  tool-proxy:
    container_name: tool-proxy
    build:
      context: ./packages/tool-proxy
      dockerfile: Dockerfile.prod
    ports:
      # - '9000:9000' # tool-watchtower
      - '9678:9678' # tool-n8n
    restart: unless-stopped
    volumes:
      - ./packages/tool-proxy/conf.d:/etc/nginx/conf.d:ro
      - ./packages/tool-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cert:/etc/nginx/cert:ro

  tool-n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: tool-n8n
    restart: always
    env_file:
      - ./packages/tool-n8n/.base.env
      - ./packages/tool-n8n/.prod.env
    command: start --tunnel
    volumes:
      - ./packages/tool-n8n/.volume:/home/node/.n8n:rw
