networks:
  app-network:
    driver: bridge

services:
  demasie-app-proxy:
    container_name: demasie-app-proxy
    image: ghcr.io/ndemasie/demasie-app-proxy:latest
    ports:
      - '10100:10100' # nathan-app-site
      - '10150:10150' # natalie-app-site
      - '10200:10200' # nathan-edu-i18next-server
      - '10300:10300' # nathan-app-habit-print
      - '10400:10400' # nathan-app-refer-codes
    restart: unless-stopped
    networks:
      - app-network

  nathan-app-site:
    container_name: nathan-app-site
    image: ghcr.io/ndemasie/nathan-app-site:latest
    restart: unless-stopped
    networks:
      - app-network

  nathan-edu-i18next-server:
    container_name: nathan-edu-i18next-server
    image: ghcr.io/ndemasie/nathan-edu-i18next-server:latest
    restart: unless-stopped
    networks:
      - app-network

  nathan-app-habit-print:
    container_name: nathan-app-habit-print
    image: ghcr.io/ndemasie/nathan-app-habit-print:latest
    restart: unless-stopped
    networks:
      - app-network

  nathan-app-refer-codes:
    container_name: nathan-app-refer-codes
    image: ghcr.io/ndemasie/nathan-app-refer-codes:latest
    restart: unless-stopped
    networks:
      - app-network
