networks:
  app-network:
    name: app-network

services:
  demasie-proxy:
    container_name: demasie-proxy
    build:
      context: ./packages/demasie-proxy
      dockerfile: Dockerfile.prod
    ports:
      - '10100:10100' # nathan-app-site
      - '10150:10150' # natalie-app-site
      - '10200:10200' # nathan-edu-i18next-server
      - '10300:10300' # nathan-app-habit-print
      - '10400:10400' # nathan-app-refer-codes
    restart: unless-stopped
    volumes:
      - ./packages/demasie-proxy/conf.d:/etc/nginx/conf.d:ro
      - ./packages/demasie-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cert:/etc/nginx/cert:ro

  nathan-app-site:
    container_name: nathan-app-site
    build:
      context: ./packages/nathan-app-site
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./packages/nathan-app-site/src:/root/src:ro
      - ./packages/nathan-app-site/public:/root/public:ro

  nathan-edu-i18next-server:
    container_name: nathan-edu-i18next-server
    build:
      context: ./packages/nathan-edu-i18next-server
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./packages/nathan-edu-i18next-server/src:/root/src:ro

  nathan-app-habit-print:
    container_name: nathan-app-habit-print
    build:
      context: ./packages/nathan-app-habit-print
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./packages/nathan-app-habit-print/src:/root/src:ro

  nathan-app-refer-codes:
    container_name: nathan-app-refer-codes
    build:
      context: ./packages/nathan-app-refer-codes
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./packages/nathan-app-refer-codes/src:/root/src:ro
      - ./packages/nathan-app-refer-codes/public:/root/public:ro
