services:
  infra-cloudflared:
    container_name: infra-cloudflared
    image: cloudflare/cloudflared
    restart: unless-stopped
    env_file: ./.env
    environment:
      - TUNNEL_TOKEN=$CLOUDFLARE_TUNNEL_TOKEN
    command: tunnel --no-autoupdate --config /etc/cloudflared/config.yml run
    volumes:
      - ./packages/infra-cloudflared/config.yml:/etc/cloudflared/config.yml:ro
    network_mode: host
