tunnel: demasie_server

loglevel: info

# Enable metrics endpoint (optional)
# metrics: 0.0.0.0:2000

# Connection settings
retries: 3
retry-interval: 10s
grace-period: 30s

protocol: quic

ingress:
  # SSH access through tunnel
  - hostname: ssh.demasie.com
    service: ssh://localhost:22
    originRequest:
      connectTimeout: 30s
      keepAliveTimeout: 90s

  - hostname: tool-watchtower.demasie.com
    service: http://tool-proxy:9000

  - hostname: demasie.com
    service: http://demasie-proxy:10100
  - hostname: www.demasie.com
    service: http://demasie-proxy:10100
  - hostname: nathan.demasie.com
    service: http://demasie-proxy:10100
  - hostname: nathan-app-site.demasie.com
    service: http://demasie-proxy:10100

  - hostname: cutie.demasie.com
    service: http://demasie-proxy:10150

  - hostname: nathan-edu-i18next-server.demasie.com
    service: http://demasie-proxy:10200

  - hostname: habit.demasie.com
    service: http://demasie-proxy:10300
  - hostname: nathan-app-habit-print.demasie.com
    service: http://demasie-proxy:10300

  - hostname: refer.demasie.com
    service: http://demasie-proxy:10400
  - hostname: nathan-app-refer-codes.demasie.com
    service: http://demasie-proxy:10400

  # Required catch-all rule - must be last
  - service: http_status:404
