name: app-proxy remove old pkgs

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 */3 * *' # 9:00 UTC-0 time every 3 days

jobs:
  remove_old_containers:
    runs-on: ubuntu-latest
    steps:
      - name: app-proxy-remove-old-pkgs
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'app-proxy'
          package-type: 'container'
          min-versions-to-keep: 5
          delete-only-untagged-versions: 'true'
