name: Github Pages Astro CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      name: github-pages
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: bash ./scripts/build.sh
        env:
          ENVIRONMENT_MODE: production

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist