name: Build and Deploy on Github Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy_site:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    environment:
      name: github-pages

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build homepage
        run: bash ./scripts/build.sh --file ./apps/homepage/Dockerfile.prod

      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
