name: Build and Deploy CI/CD for EC2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy_ec2:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    environment:
      name: github-pages

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.AWS_EC2_PUBLIC_DNS }}
          REMOTE_USER: ${{ secrets.AWS_EC2_USER }}
          TARGET: "./demasie.com"

      - name: Run
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.SSH_HOST}}
            USER_NAME: ${secrets.USER_NAME}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

              cd ${HOME}/demasie.com &&
              npm run docker:deploy
              '