name: Deploy to Github Pages

on:
  push:
    branches: [ main ]
  # Allows running this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

env:
  ENVIRONMENT_MODE: production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v2

      - name: Install, build, and upload your site
        uses: withastro/action@v0

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
        id: deployment