name: publish ghcr app-referral-codes
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'packages/app-referral-codes/**'

env:
  IMAGE_NAME: app-referral-codes
  REGISTRY: ghcr.io

jobs:
  publish_container:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build image
        run: |
          docker build ./packages/${{env.IMAGE_NAME}} --file ./packages/${{env.IMAGE_NAME}}/Dockerfile.prod --tag ${{REGISTRY}}/${{github.actor}}/${{env.IMAGE_NAME}}:latest

      - name: push image
        run: |
          echo "${{secrets.GITHUB_TOKEN}}" | docker login ${{REGISTRY}} -u ${{github.actor}} --password-stdin
          docker push ${{REGISTRY}}/${{github.actor}}/${{env.IMAGE_NAME}}:latest
