name: pkg remove old

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9 */3 * *' # 9:00 UTC-0 time every 3 days

jobs:
  remove_old_containers:
    runs-on: ubuntu-latest
    steps:
      - name: remove-nathan-app-habit-print
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'nathan-app-habit-print'
          package-type: 'container'
          min-versions-to-keep: 5
          delete-only-untagged-versions: 'true'

      - name: remove-nathan-app-refer-codes
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'nathan-app-refer-codes'
          package-type: 'container'
          min-versions-to-keep: 5
          delete-only-untagged-versions: 'true'

      - name: remove-nginx-demise
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'demasie-proxy'
          package-type: 'container'
          min-versions-to-keep: 5
          delete-only-untagged-versions: 'true'

      - name: remove-nathan-edu-i18next-server
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'nathan-edu-i18next-server'
          package-type: 'container'
          min-versions-to-keep: 5
          delete-only-untagged-versions: 'true'

      - name: remove-nathan-app-site
        uses: actions/delete-package-versions@v5
        with:
          package-name: 'nathan-app-site'
          package-type: 'container'
          min-versions-to-keep: 5
          delete-only-untagged-versions: 'true'
