name: trigger tool-watchtower

on:
  workflow_dispatch:
  workflow_call:

jobs:
  trigger_watchtower:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Watchtower via update url
        run: |
          curl \
            --header "Authorization: Bearer ${{secrets.WATCHTOWER_HTTP_API_TOKEN}}" \
            --silent \
            --show-error \
            --max-time 10 \
            https://tool-watchtower.demasie.com/v1/update
